import "./globals.css";

export const metadata = {
  title: "AiGenda",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="ru">
      <body
        className="antialiased"
      >
        {children}
      </body>
    </html>
  );
}
