import "./globals.css";
import { StyledComponentsRegistry } from "./providers/StyledComponentsRegistry";

export const metadata = {
  title: "AiGenda",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="ru">
      <body
        className="antialiased"
      >
        <StyledComponentsRegistry>
          {children}
        </StyledComponentsRegistry>
      </body>
    </html>
  );
}
